# Generated by Django 2.1 on 2018-08-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
