# Generated by Django 2.1 on 2018-08-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceModel', '0002_auto_20180822_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_class', models.CharField(max_length=5)),
                ('total_present', models.CharField(max_length=5)),
                ('total_absent', models.CharField(max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceModel.Student')),
            ],
        ),
    ]
